COMBO_ENABLE        = yes
CONSOLE_ENABLE      = no
DEBUG_ENABLE        = no
EXTRAKEY_ENABLE     = yes
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE       = yes
LTO_ENABLE          = yes
MAGIC_ENABLE        = no
MIDI_ENABLE         = no
MOUSEKEY_ENABLE     = yes      # Mouse keys
MUSIC_ENABLE        = no
NKRO_ENABLE         = yes      # Enable N-Key Rollover
OLED_ENABLE         = yes
RGBLIGHT_ENABLE     = yes      # Enable WS2812 RGB underlight.
TAP_DANCE_ENABLE    = yes
VIA_ENABLE          = no      # Enable VIA
